#!/bin/bash
# Factory IQC script to measure battery capacity

# Error if we try to use an undefined variable
# set -u


# These are used by the logfile header
PRGNAME="olpc-batcap"
VERSION="0.2.5"

echo -n "$PRGNAME Ver: $VERSION starting at "
echo `date`

if [ -e ./olpc-pwr-common ]; then
	source "./olpc-pwr-common"
elif [ -e /usr/share/olpc-utils/olpc-pwr-common ]; then
	source /usr/share/olpc-utils/olpc-pwr-common
else
	echo "Can't find 'olpc-pwr-common'"
	exit 1
fi

# Make sure that if we exit via ctrl-C that
# charging gets turned back on.
function cleanup
{
	enable_charging
	exit
}

trap cleanup SIGINT

echo "Disabling powerd daemon"

if [ -e /usr/bin/systemctl ]; then
	sudo systemctl stop powerd.service
else
	sudo stop powerd
fi

pwrlog_module_init

echo "Waiting for a battery"
wait_for_battery
echo "Reading battery info"
pwrlog_battery_init

BATTERY_LOW_VOL=5100000

get_chemistry BATTERY_CHEM

if [[ "${BATTERY_CHEM}" == "NiMH" ]]; then
	echo "NiMH Chemistry detected"
	BATTERY_LOW_VOL=5180000
fi

echo
echo "PRECHARGE"
echo

# Make sure we aren't in discharge mode
enable_charging
# Allow the status to update
sleep 1

# when battery status is full, stop charging.
# so capacity can be 93~100 when status is full
# prevent this case, discharge to below 93

get_sta BATTERY_STATUS
if  [[ "${BATTERY_STATUS}" == "Discharging" ]]; then
   echo "Battery status: $BATTERY_STATUS"
   echo "***Please plug AC input or try to replug AC adapter"

   while [[ "${BATTERY_STATUS}" == "Discharging" ]]
   do
	sleep 1
	get_sta BATTERY_STATUS
   done
fi

echo "Topping off the battery"

# With EC code > 0.4.02 enterning into runin discharge mode
# will clear the battery full flag.
disable_charging
sleep 2
enable_charging

while true
do
    get_soc BATTERY_SOC
    get_sta BATTERY_STATUS
    get_cur BATTERY_CUR
    get_vol BATTERY_VOL
    get_temp BATTERY_TEMP
    VOLT_100s=$(( ${BATTERY_VOL}/10000 ))
    VOLT_STR=$(format_hundreds_as_n.nn $VOLT_100s)
    TEMP_STR=$(format_hundreds_as_n.nn $BATTERY_TEMP)

    echo "Precharge: SOC: ${BATTERY_SOC}, $(( ${BATTERY_CUR}/1000 )) mA,  ${VOLT_STR} V, ${TEMP_STR} degC "

    if [[ ${BATTERY_STATUS} == "Full" ]]; then
	echo "Battery status: ${BATTERY_STATUS}"
	break
    fi
    sleep 5
done

# Accuracy of the sensor is +/- 2 degC.  I'd like to have this number lower but I found
# testing at the OLPC office that many of the batterys can sit for very long periods
# waiting for the temp to decrease. (Office temp 25-30 deg C)
# TODO: Change this to and adaptive scheme. So it will work regardless of the ambient
# temp

COOLING_TEMP=3080

echo "Waiting for battery to cool below $(format_hundreds_as_n.nn $COOLING_TEMP) C"
get_temp BATTERY_TEMP
echo "Start temp: $(format_hundreds_as_n.nn $BATTERY_TEMP) C"
START_TIME=$(get_seconds)
while true
do
    get_temp BATTERY_TEMP
    # Only show the updated on the screen not in the logs
    printf "Temperature: $(format_hundreds_as_n.nn $BATTERY_TEMP) C seconds: $(( $(get_seconds) - $START_TIME )) \r" >&2
    if [[ ${BATTERY_TEMP} -lt ${COOLING_TEMP} ]] ; then
	echo
        echo "Battery cooled to $(format_hundreds_as_n.nn $BATTERY_TEMP) C"
        break
    fi
    sleep 1
done
echo "Cooling took $(( $(get_seconds) - $START_TIME )) seconds"

echo
echo "DISCHARGE"
echo

FDATE=`date "+%y%m%d-%H%M%S"`
HOST=`hostname -s`
LOGFILE="dis-$DS_SERNUM-$FDATE.csv"
pwrlog_write_header

set_backlight_full

# Set the discharge current by running a few other tasks.
# The current draw can be changed by changing the master volume
# level.
# For 1.75 83% works out to ~850mA and 70% is ~700mA.

if [[ $XO_VERSION == "4" ]]; then
	amixer set Master 0% unmute > /dev/null
else
	amixer set Speaker 100% unmute > /dev/null
	amixer set Master 83% unmute > /dev/null
fi

gst-launch audiotestsrc volume=1 freq=100 ! audio/x-raw-int, width=16, channels=2 ! alsasink > /dev/null 2>&1 &
AUDIO_PID=$!
# Give audio maximum prioity so it does not skip.
sudo chrt -p 99 $AUDIO_PID

sh /runin/runin-camera > /dev/null 2>&1 &
CAMERA_PID=$!

init_readings
take_reading
log_reading

disable_charging

while true
do
    take_reading
    log_reading
    VOLT_100s=$(( ${VOLT}/10000 ))
    VOLT_STR=$(format_hundreds_as_n.nn $VOLT_100s)
    get_cur BATTERY_CUR
    get_temp BATTERY_TEMP
    TEMP_STR=$(format_hundreds_as_n.nn $BATTERY_TEMP)
    printf "Discharge: SOC: %d %%, %4d mAh, %s V, %4d mA, %s degC\n"  $CAPLEVEL $MAh_NET $VOLT_STR $(( ${BATTERY_CUR}/1000 )) $TEMP_STR

    if [[ ( $VOLT -le ${BATTERY_LOW_VOL} ) ]]; then
       echo "Low voltage threshold reached. Test Complete."
       break
    fi

    if [[ (${VOLT} -le 5400000) && (${VOLT} -ge 5250000) ]]; then
        sleep 5
    elif [[ ( ${VOLT} -le 5250000 ) ]]; then
	sleep 1
    else
        sleep 20
    fi
done

FDATE=`date "+%y%m%d-%H%M%S"`
LOGFILE="chg-$DS_SERNUM-$FDATE.csv"
pwrlog_write_header
init_readings
take_reading
log_reading

echo
echo "CHARGE"
echo

# echo "enable charge"
enable_charging

# No point in using lots of extra power while charging
# Stop the loading apps.
kill $CAMERA_PID > /dev/null
kill $AUDIO_PID > /dev/null
killall gst-launch-0.10 > /dev/null

while true
do
    take_reading
    log_reading
    VOLT_100s=$(( ${VOLT}/10000 ))
    VOLT_STR=$(format_hundreds_as_n.nn $VOLT_100s)
    get_cur BATTERY_CUR
    get_temp BATTERY_TEMP
    TEMP_STR=$(format_hundreds_as_n.nn $BATTERY_TEMP)
    printf "Charge: SOC: %d %%, %4d mAh, %s V, %4d mA, %s degC\n"  $CAPLEVEL $MAh_NET $VOLT_STR $(( ${BATTERY_CUR}/1000 )) $TEMP_STR

    if [[ ${STAT} == "Full" ]]; then
        echo "Charge complete. Exiting"
        break
    fi

    sleep 20
done

echo -n "$PRGNAME ending at "
echo `date`
